# Generated by Django 5.0.3 on 2024-03-13 13:02

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pics', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('current_course', models.CharField(choices=[('CS', 'Computer Science Department'), ('ENG', 'English Literature Department'), ('MATH', 'Mathematics Department'), ('CHEM', 'Chemistry Department'), ('PHYS', 'Physics Department'), ('HIST', 'History Department'), ('PSYC', 'Psychology Department'), ('BIO', 'Biology Department'), ('ART', 'Fine Arts Department'), ('ECON', 'Economics Department'), ('PHIL', 'Philosophy Department'), ('BUS', 'Business Administration Department'), ('EDUC', 'Education Department'), ('MED', 'Medical Department'), ('LAW', 'Law Department'), ('ARCH', 'Architecture Department'), ('MUSIC', 'Music Department'), ('NURS', 'Nursing Department'), ('COMM', 'Communication Studies Department'), ('SOC', 'Sociology Department')], max_length=6)),
                ('staff_id', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pics', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('current_course', models.CharField(choices=[('CS101', 'BSc in Computer Science'), ('ENG201', 'BA in English Literature'), ('MATH301', 'BSc in Mathematics'), ('CHEM101', 'BSc in Chemistry'), ('PHYS202', 'BSc in Physics'), ('HIST102', 'BA in History'), ('PSYC301', 'BSc in Psychology'), ('BIO101', 'BSc in Biology'), ('ART205', 'BFA in Fine Arts'), ('ECON202', 'BSc in Economics'), ('PHIL101', 'BA in Philosophy'), ('BUS301', 'BBA'), ('EDUC202', 'Bachelor of Education'), ('MED101', 'MBBS'), ('LAW201', 'LLB'), ('ARCH301', 'BArch'), ('MUSIC202', 'BMus'), ('NURS101', 'BSN'), ('COMM301', 'BA in Communication Studies'), ('SOC101', 'BA in Sociology')], max_length=10)),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
