# Generated by Django 5.0.3 on 2024-03-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_admin_remove_staff_user_remove_student_user_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PC/Laptop', 'Pc/Laptop'), ('VR Headset', 'Vr Headset'), ('Camera/Sensor', 'Camera/Sensor'), ('PC Peripherals', 'Pc Peripherals'), ('Furniture', 'Furniture'), ('Tripod', 'Tripod'), ('Other', 'Other'), ('VR Controller', 'Vr Controller'), ('Phones/Tablets', 'Phones/Tablets')], max_length=25)),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Available', 'Available'), ('Decommissioned', 'Decommissioned'), ('Unavailable', 'Unavailable')], max_length=15)),
                ('quantity', models.IntegerField()),
                ('last_audit', models.DateField()),
            ],
        ),
    ]
