# Generated by Django 5.0.3 on 2024-03-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='current_course',
            new_name='department',
        ),
    ]
