# Generated by Django 5.0.3 on 2024-03-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0005_rename_current_course_staff_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('Pend', 'Pending'), ('Avail', 'Available'), ('Decom', 'Decommissioned'), ('Unavail', 'Unavailable')], max_length=15),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('PC', 'PC/Laptop'), ('VRH', 'VR Headset'), ('CS', 'Camera/Sensor'), ('PP', 'PC Peripherals'), ('Furn', 'Furniture'), ('Trip', 'Tripod'), ('Oth', 'Other'), ('VRC', 'VR Controller'), ('PT', 'Phones/Tablets')], max_length=25),
        ),
    ]
