# Generated by Django 5.0.3 on 2024-03-27 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0006_alter_equipment_status_alter_equipment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='profile_pics',
            new_name='profile_pic',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='profile_pics',
            new_name='profile_pic',
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Bookings.equipment'),
            preserve_default=False,
        ),
    ]
