# Generated by Django 5.0.3 on 2024-04-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0007_rename_profile_pics_staff_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='comment',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
