# Generated by Django 5.0.3 on 2024-04-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0008_equipment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('PC', 'PC/Laptop'), ('VRH', 'VR Headset'), ('CS', 'Camera/Sensors'), ('PP', 'PC Peripherals'), ('Furn', 'Furniture'), ('Trip', 'Tripod'), ('Oth', 'Other'), ('VRC', 'VR Controller'), ('PT', 'Phones/Tablets'), ('PCBL', 'Power/Cable')], max_length=25),
        ),
    ]
