# Generated by Django 5.0.3 on 2024-04-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0009_alter_equipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('Pend', 'Pending'), ('Avail', 'Available'), ('Decom', 'Decommisioned'), ('Unavail', 'Unavailable'), ('Loan', 'On Loan'), ('Repair', 'Repairing')], max_length=15),
        ),
    ]
