# Generated by Django 5.0.3 on 2024-05-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0010_alter_equipment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='approvalStatus',
            new_name='approval_status',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='returnDate',
            new_name='return_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='returnStatus',
            new_name='return_status',
        ),
    ]
