# Generated by Django 5.0.3 on 2024-05-01 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0011_rename_approvalstatus_booking_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reason',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by', to='Bookings.admin'),
        ),
    ]
