# Generated by Django 5.0.3 on 2024-05-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0012_booking_reason_alter_booking_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='approval_status',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='return_status',
            new_name='returned',
        ),
    ]
