# Generated by Django 5.0.3 on 2024-05-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0011_report'),
        ('Bookings', '0013_rename_approval_status_booking_approved_and_more'),
    ]

    operations = [
    ]
