# Generated by Django 5.0.3 on 2024-05-01 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0014_merge_20240501_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='from_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
